const OFFICIAL={guide:'https://www.jbe.go.kr/board/list.jbe?boardId=BBS_0000085&menuCd=DOM_000000106002002000&contentsSid=336&cpath=',manual:'https://www.jbe.go.kr/board/list.jbe?boardId=BBS_0000010&menuCd=DOM_000000106005000000&contentsSid=346&cpath='};
const makeWork=(name,desc,steps)=>({name,desc,resources:[['전북교육청 행정업무 길라잡이',OFFICIAL.guide],['전북교육청 업무매뉴얼',OFFICIAL.manual]],steps:steps.map((title,i)=>({title,summary:`${title} 단계의 처리사항을 확인합니다.`,type:i===steps.length-1?'approve':i%3===0?'check':'do',todo:[`${title}에 필요한 최신 기준과 기관 내부 절차를 확인합니다.`, '담당자·처리기한·결재선을 확인하고 업무시스템에 정확히 반영합니다.'],docs:['관련 법령·지침','업무시스템 입력자료 및 증빙'],check:`${title} 처리 결과와 결재·기록 상태가 서로 일치하는지 확인합니다.`}))});
const areas=[
 {id:'people',no:'01',name:'인사·복무를 관리',short:'인사·복무',desc:'신규 적응, 복무, 보수·세무와 교육공무직 인사 흐름',works:[makeWork('신규 기본','처음 맡은 교육행정 업무의 기본 흐름',['업무 환경 확인','업무분장·기관 기준 확인','연간 일정 정리','업무시스템 접근 확인']),makeWork('복무','근무·휴가·출장 등 복무 처리',['신청 내용 확인','복무 기준 검토','업무 공백 확인','시스템 입력','결재 및 기록 관리']),makeWork('지방공무원 인사','임용·전보·승진·교육 등 인사 업무',['인사 사유 확인','관련 기준 검토','자료 작성·제출','인사시스템 처리','결재·통보','인사기록 정리']),makeWork('보수·세무','급여·수당·공제·연말정산 업무',['지급 대상 확인','변동자료 수합','급여 산정','지급액 검증','결재·지급','세무 신고·정산']),makeWork('공무직·계약인력','채용·계약·근태·퇴직 처리',['채용 필요 확인','채용 절차 진행','계약 체결','근태·보수 관리','변경·종료 처리','기록 보존'])]},
 {id:'income',no:'02',name:'돈을 받거나 보관',short:'세입·보관',desc:'학교로 들어오거나 별도로 보관하는 자금의 흐름',works:[makeWork('학교회계 세입·자금','수입과 자금의 수납·관리',['수입 근거 확인','징수 결정','납부 고지','수납 처리','수입일계 확인','자금 대사']),makeWork('세입세출외현금','보증금·원천세 등 보관금 관리',['보관금 성격 확인','수납 등록','보관금 대사','반환·납부 결정','지급 처리','장부 마감']),makeWork('학교발전기금','발전기금 조성·운용·결산',['기탁 접수','운용계획 수립','위원회 심의','기금 집행','결산 작성','결과 공개'])]},
 {id:'expense',no:'03',name:'예산을 세우고 계약·지출',short:'예산·지출',desc:'학교회계 예산 편성부터 계약, 검수, 지급과 결산까지 이어지는 흐름',works:[makeWork('학교회계 예산','본예산·추경·성립전예산 편성과 관리',['편성 기준 확인','사업 요구 수합','요구액 검토·조정','예산안 작성','심의·확정','예산 공개']),makeWork('세출','품의부터 지급·결산까지의 지출',['예산·집행 기준 확인','지출 품의','원인행위','검사·검수','지출결의','대금 지급','증빙 정리']),makeWork('계약','공사·물품·용역 계약 절차',['계약 범위·금액 산정','계약 방법 결정','사전규격·공고','업체 선정','계약 체결','이행·검수','대가 지급'])]},
 {id:'asset',no:'04',name:'재산·시설·안전을 관리',short:'재산·시설',desc:'물품과 공유재산, 시설 유지와 안전보건의 생애주기',works:[makeWork('물품 관리','취득·사용·재물조사·처분',['관리대상 판정','취득·검수','물품대장 등록','사용·이동 관리','재물조사','불용·처분']),makeWork('공유재산','재산 취득·사용허가·대부·처분',['재산 현황 확인','취득·등기','재산대장 등록','사용허가·대부','실태조사','정비·처분']),makeWork('시설·안전','시설 점검·공사·재난·산업안전 관리',['점검계획 수립','현장 점검','위험도 판단','긴급조치','보수·공사','완료 확인·이력관리'])]},
 {id:'school',no:'05',name:'학교 운영과 행정을 지원',short:'학교 운영',desc:'문서·기록·민원·정보공개·학교운영위원회와 교육행정데이터 활용 업무',works:[makeWork('학교운영위원회','안건 접수부터 회의·결과 공개',['안건 접수','회의 소집','자료 준비','안건 심의','결과 통보','회의록 공개']),makeWork('민원·제증명','민원 접수와 제증명 발급',['신청권 확인','민원 접수','관련 기록 조회','사실 검토','처리·발급','결과 기록']),makeWork('공문서(기록물)','문서 생산·접수·분류·이관·폐기',['문서 생산·접수','등록·분류','검토·결재','시행','편철·보존','이관·평가']),makeWork('교육행정데이터','자료 수집·검증·분석·공개',['요구사항 확인','자료 수집','오류 검증','분석·가공','보고·공개','보안·보존 관리'])]},
 {id:'office',no:'06',name:'교육청 예산을 집행',short:'교육청 예산',desc:'교육비특별회계의 예산·지출·수입·결산 구조',badge:'교육청 전용',works:[makeWork('교특회계','교육비특별회계 업무 전반',['예산 편성·배정','수입·자금 관리','지출 원인행위','계약·검수','지출·수납','결산·보고'])]}
];
const $=s=>document.querySelector(s),areaSection=$('#areaSection'),areaGrid=$('#areaGrid'),intro=$('.map-intro'),workspace=$('#workspace'),searchResults=$('#searchResults');let currentArea,currentWork;
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function renderAreas(){areaGrid.innerHTML=areas.map((a,ai)=>`<article class="area-panel area-${ai+1}" style="--accent:${['#3979ad','#c27335','#27876c','#a0476d','#6d58a7','#258589'][ai]}"><header><div><small>AREA ${a.no}</small><h3>${a.name}</h3></div><b>${a.badge||a.works.length+'개 업무'}</b></header><p>${a.desc}</p><div>${a.works.map((w,i)=>`<button data-area="${a.id}" data-work="${i}"><span><strong>${w.name}</strong><small>${w.steps.length}개 하위 흐름</small></span><i>→</i></button>`).join('')}</div></article>`).join('');areaGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>openArea(b.dataset.area,+b.dataset.work))}
function openArea(id,workIndex=0){currentArea=areas.find(a=>a.id===id);currentWork=currentArea.works[workIndex];areaSection.hidden=true;intro.hidden=true;searchResults.hidden=true;workspace.hidden=false;$('#areaName').textContent=currentArea.short;$('#workTitle').textContent=currentWork.name;$('#workDesc').textContent=currentWork.desc;renderTabs();renderWork();scrollTo({top:0,behavior:'smooth'})}
function renderTabs(){const tabs=$('#workTabs');tabs.innerHTML=currentArea.works.map((w,i)=>`<button class="${w===currentWork?'active':''}" role="tab" data-index="${i}">${esc(w.name)}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentWork=currentArea.works[+b.dataset.index];$('#workTitle').textContent=currentWork.name;$('#workDesc').textContent=currentWork.desc;renderTabs();renderWork()})}
function renderWork(){const flow=$('#flowList');flow.innerHTML=currentWork.steps.map((s,i)=>`${i?'<div class="flow-arrow"></div>':''}<button class="step-card" data-step="${i}" data-type="${s.type}"><span class="step-num">${String(i+1).padStart(2,'0')}</span><span><b>${esc(s.title)}</b><small>${esc(s.summary)}</small></span><i>›</i></button>`).join('');flow.querySelectorAll('button').forEach(b=>b.onclick=()=>showStep(+b.dataset.step));const unique=[...new Map(currentWork.resources.map(r=>[r[1],r])).values()];$('#resourceCount').textContent=unique.length;$('#resourceList').innerHTML=unique.map(r=>`<a class="resource-link" href="${r[1]}" target="_blank" rel="noopener"><b>${esc(r[0])}</b><small>공식 원문 ↗</small></a>`).join('');$('#detailPanel').innerHTML='<div class="detail-empty"><span>☞</span><b>단계를 선택하세요</b><p>해야 할 일, 준비자료와 완료 확인사항을 볼 수 있습니다.</p></div>'}
function showStep(i){const s=currentWork.steps[i];document.querySelectorAll('.step-card').forEach((b,n)=>b.classList.toggle('active',n===i));$('#detailPanel').innerHTML=`<div class="detail-content"><header><small>STEP ${String(i+1).padStart(2,'0')}</small><h3>${esc(s.title)}</h3><p>${esc(s.summary)}</p></header><div><section class="detail-block"><h4>해야 할 일</h4><ul>${s.todo.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="detail-block"><h4>준비자료</h4><ul>${s.docs.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="detail-block"><h4>완료 확인·주의</h4><p class="complete">${esc(s.check)}</p></section></div></div>`}
function allMatches(q){const out=[];areas.forEach(a=>a.works.forEach((w,wi)=>{if(`${a.name} ${w.name} ${w.desc} ${w.steps.map(s=>s.title).join(' ')}`.includes(q))out.push({a,w,wi})}));return out}
function search(q){q=q.trim();if(!q){searchResults.hidden=true;workspace.hidden=true;areaSection.hidden=false;intro.hidden=false;return}const hits=allMatches(q);intro.hidden=true;areaSection.hidden=true;workspace.hidden=true;searchResults.hidden=false;$('#searchCount').textContent=hits.length;$('#searchList').innerHTML=hits.map((x,i)=>`<button class="search-item" data-i="${i}"><span>${x.a.short}</span><b>${esc(x.w.name)}</b><small>${esc(x.w.desc)} →</small></button>`).join('')||'<p>검색 결과가 없습니다. 다른 업무명이나 단계로 검색해 주세요.</p>';$('#searchList').querySelectorAll('button').forEach(b=>b.onclick=()=>openArea(hits[+b.dataset.i].a.id,hits[+b.dataset.i].wi))}
$('#searchInput').addEventListener('input',e=>search(e.target.value));$('#clearSearch').onclick=()=>{$('#searchInput').value='';search('');$('#searchInput').focus()};$('#backButton').onclick=()=>{workspace.hidden=true;areaSection.hidden=false;intro.hidden=false;scrollTo({top:0,behavior:'smooth'})};$('#resourceButton').onclick=()=>$('#related').scrollIntoView({behavior:'smooth'});$('#helpButton').onclick=()=>$('#helpDialog').showModal();$('#closeHelp').onclick=$('#startButton').onclick=()=>$('#helpDialog').close();$('#themeButton').onclick=()=>document.body.classList.toggle('dark');renderAreas();
